// Auth
export const CHECK_USER_LOGINED = 'CHECK_USER_LOGINED';
export const USER_LOGINED = 'USER_LOGINED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGOUT_USER = 'LOGOUT_USER';